(cd ../auth-service && git pull)
(cd ../database && git pull)
(cd ../front-end && git pull)
(cd ../fs-service && git pull)
(cd ../gateway && git pull)
(cd ../order-service && git pull)
(cd ../product-service && git pull)